CREATE TABLE aluno (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ra VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    email VARCHAR(255)
);