spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      patch: /h2-console
